// Functions Prototypes-------------------------------------------------------------------
void check_reset();
void relogio();
void ledvm();
void ledaz();
void ledam();
void ledvd();
void menu_system();
void nivel_dog(int nivel);
void nivel_cat(int nivel);
void Serial_check(String Com_S);
void listDir(fs::FS &fs, const char * dirname, uint8_t levels);
void createDir(fs::FS &fs, const char * path);
void removeDir(fs::FS &fs, const char * path);
void readFile(fs::FS &fs, const char * path);
String read_saved_times(fs::FS &fs, const char * path);
String read_saved(fs::FS &fs, const char * path);
void appendFile_creating(fs::FS &fs, const char * path, const char * message);
void writeFile(fs::FS &fs, const char * path, const char * message);
void appendFile(fs::FS &fs, const char * path, const char * message);
void renameFile(fs::FS &fs, const char * path1, const char * path2);
void deleteFile(fs::FS &fs, const char * path);
void writeFile2(fs::FS &fs, const char * path, const char * message);
void deleteFile2(fs::FS &fs, const char * path);
void read_prog_index(fs::FS &fs, const char * path);
void hard_reset();
void leprog();
void init_sd_card();
void init_display();
void drawtext(String text, uint16_t color,uint16_t bgcolor, uint8_t col_txt, uint8_t lin_txt, uint8_t txtsz);
void desenha_pet_logo();
void desenha_logo();
void desenha_dog();
void desenha_cat();
void desenha_wifi();
void desenha_wifi(String wifi_level);
int check_wifi_level();
void pet_food();
void wifi_led_status();
void wifi_icon_refresh(int level_code);
void nivel_res_refresh();
void refresh_ihm();
void calendario();
void get_config();
void init_system();
void select_menu_prog();
String lv_dog_res();
String lv_cat_res();
bool bt_ok();
bool bt_set();
bool bt_down();
bool bt_up();
void check_buttons();
void init_menu();
void color_dog_prog(int d1, int bd1, int d2,int bd2,int d3,int bd3, int d4,int bd4);
void color_cat_prog(int c1, int bc1, int c2,int bc2,int c3,int bc3, int c4,int bc4);
void menu_system_prog();
void set_prog();
void prog_selected();
void save_selected_file();
void stop_disp();
void check_prog_clock_dog();
void check_prog_clock_cat();
void update_prog_index();
void update_prog_data();
void reset_all_files();
void wifi_start();
void ntp_start();
void firebase_start();
void check_flag_menu();
void check_serial();
void read_prog_file();
void check_program();
void select_menu_fuso();
void fuso_menu();
void save_fuso_prog();
void wifi_reset();
void mqtt_start();
String subscreve();
void publica();
void one_beep(int tb);
void three_beep();
void check_mqtt();
void feed_cat();
void feed_dog();
void publish_schedule();
void pub_lvsl();
void music();
void disableJTAG();
void attach_servo(gpio_num_t pin, ledc_channel_t channel);
void wifi_reconnect_if_needed();
void connect_Wifi();
